sla = Airport.create(name: 'Martín Miguel de Güemes International Airport', city: 'Salta', code: 'SLA')
mdq = Airport.create(name: 'Astor Piazzolla International Airport', city: 'Mar del Plata', code: 'MDQ')
eze = Airport.create(name: 'Ministro Pistarini International Airport', city: 'Ezeiza', code: 'EZE')
nyc = Airport.create(name: 'John F. Kennedy International Airport', city: 'New York', code: 'NYC')
lax = Airport.create(name: 'Los Angeles International Airport', city: 'Los Ángeles', code: 'LAX')
mex = Airport.create(name: 'Ciudad de México International Airport', city: 'Ciudad de México', code: 'MEX')
cdg = Airport.create(name: 'Charles-de-Gaulle International Airport', city: 'Paris', code: 'CDG')
lis = Airport.create(name: 'Humberto Delgado International Airport', city: 'Lisboa', code: 'LIS')
mxp = Airport.create(name: 'Malpensa International Airport', city: 'Milán', code: 'MXP')
muc = Airport.create(name: 'Franz Josef Strauss International Airport', city: 'Munich', code: 'MUC')
zrh = Airport.create(name: 'Zúrich International Airport', city: 'Zúrich', code: 'ZRH')
dub = Airport.create(name: 'Dublín International Airport', city: 'Dublín', code: 'DUB')
opo = Airport.create(name: 'Porto International Airport', city: 'Porto', code: 'OPO')
fra = Airport.create(name: 'Frankfurt Airport', city: 'Frankfurt', code: 'FRA')
lhr = Airport.create(name: 'London Heathrow Airport', city: 'Londres', code: 'LHR')
nrt = Airport.create(name: 'Narita International Airport', city: 'Narita', code: 'NRT')
vie = Airport.create(name: 'Vienna International Airport', city: 'Vienna', code: 'VIE')
mia = Airport.create(name: 'Miami International Airport', city: 'Miami', code: 'MIA')
pek = Airport.create(name: 'Beijing Capital International Airport', city: 'Beijing', code: 'PEK')
dmk = Airport.create(name: 'Don Mueang International Airport', city: 'Bangkok', code: 'DMK')

Flight.create(departure_airport_id: sla.id, arrival_airport_id: mdq.id, date: '02/01/2023', duration: 2, passagers: 20)
Flight.create(departure_airport_id: eze.id, arrival_airport_id: lax.id, date: '03/01/2023', duration: 8, passagers: 10)
Flight.create(departure_airport_id: eze.id, arrival_airport_id: mia.id, date: '04/01/2023', duration: 2, passagers: 5)
Flight.create(departure_airport_id: mia.id, arrival_airport_id: lax.id, date: '03/01/2023', duration: 5, passagers: 10)
Flight.create(departure_airport_id: nrt.id, arrival_airport_id: cdg.id, date: '05/01/2023', duration: 2, passagers: 10)
Flight.create(departure_airport_id: zrh.id, arrival_airport_id: muc.id, date: '04/01/2023', duration: 3, passagers: 10)
Flight.create(departure_airport_id: dmk.id, arrival_airport_id: pek.id, date: '07/01/2023', duration: 6, passagers: 20)
Flight.create(departure_airport_id: vie.id, arrival_airport_id: dub.id, date: '05/01/2023', duration: 12, passagers: 10)
Flight.create(departure_airport_id: opo.id, arrival_airport_id: lhr.id, date: '11/01/2023', duration: 4, passagers: 10)
Flight.create(departure_airport_id: mxp.id, arrival_airport_id: eze.id, date: '09/01/2023', duration: 2, passagers: 30)
Flight.create(departure_airport_id: fra.id, arrival_airport_id: lis.id, date: '12/01/2023', duration: 4, passagers: 10)
Flight.create(departure_airport_id: nyc.id, arrival_airport_id: mex.id, date: '09/01/2023', duration: 3, passagers: 30)
